site_name: Viaduct
site_url: https://viaduct.airbnb.tech/
site_description: A modern multi-tenant GraphQL server
site_author: Airbnb, Inc.
copyright: 'Copyright &copy; 2025 Airbnb, Inc. | <a href="https://creativecommons.org/licenses/by/4.0">CC BY 4.0</a>'

repo_url: https://github.com/airbnb/viaduct
repo_name: airbnb/viaduct
edit_uri: edit/master/docs/docs/

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo-only-white.svg
  favicon: assets/images/favicon.ico
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/brand.css
  - kdoc-service-styles.css
  - kdoc-styles.css

plugins:
  - search
  - blog:
      blog_dir: blog
  - macros:
      module_name: plugins/code_snippets
      on_error_fail: true

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - footnotes
  - meta
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - getting_started/index.md
    - Setup:
      - getting_started/setup/index.md
      - Clone Existing Tenant: getting_started/setup/clone/index.md
      - From Scratch: getting_started/setup/from_scratch/index.md
    - Tour: getting_started/tour/index.md
    - Star Wars Tutorial:
      - getting_started/starwars/index.md
      - Core Concepts:
        - getting_started/starwars/core/index.md
        - Node Resolvers: getting_started/starwars/core/node_resolvers.md
        - Field Resolvers: getting_started/starwars/core/field_resolvers.md
        - Batch Resolvers: getting_started/starwars/core/batch_resolvers.md
        - Global IDs: getting_started/starwars/core/global_id.md
        - Resolver Integrations: getting_started/starwars/core/resolver_integrations.md
      - Directives:
        - getting_started/starwars/directives/index.md
        - Backing Data: getting_started/starwars/directives/backing_data.md
        - Scope: getting_started/starwars/directives/scope.md
        - IDOf: getting_started/starwars/directives/idof.md
        - OneOf: getting_started/starwars/directives/oneof.md
        - Connection: getting_started/starwars/directives/connection.md
        - Edge: getting_started/starwars/directives/edge.md
      - Pagination: getting_started/starwars/pagination/index.md
      - Mutations: getting_started/starwars/mutations/index.md
      - Variables: getting_started/starwars/variables/index.md
      - Request Context: getting_started/starwars/requestcontext/index.md
      - Testing: getting_started/starwars/testing/index.md
      - Architecture:
        - getting_started/starwars/architecture/index.md
        - Schemas: getting_started/starwars/architecture/schemas.md
        - Tenants: getting_started/starwars/architecture/tenants.md
        - Viaduct Builder: getting_started/starwars/architecture/viaduct_builder.md
    - Extending: getting_started/extending/index.md
  - Documentation:
    - docs/index.md
    - Developers:
      - docs/developers/index.md
      - Resolvers:
        - docs/developers/resolvers/index.md
        - Resolver Annotation: docs/developers/resolvers/resolver_annotation.md
        - Node Resolvers: docs/developers/resolvers/node_resolvers.md
        - Field Resolvers: docs/developers/resolvers/field_resolvers.md
        - Batch Resolution: docs/developers/resolvers/batch_resolution.md
        - Mutations: docs/developers/resolvers/mutations.md
        - Node References: docs/developers/resolvers/node_references.md
      - Generated Code: docs/developers/generated_code/index.md
      - Global IDs: docs/developers/globalids/index.md
      - Scopes: docs/developers/scopes/index.md
      - Schema Reference: docs/developers/schema_reference/index.md
      - Serve: docs/developers/serve/index.md
    - Service Engineers:
      - docs/service_engineers/index.md
      - Schema Extensions: docs/service_engineers/schema_extensions/index.md
      - Multi-tenancy: docs/service_engineers/multi_tenancy/index.md
      - Observability:
        - docs/service_engineers/observability/index.md
        - Error Handling: docs/service_engineers/observability/error_handling.md
  - Contributors:
    - docs/contributors/index.md
    - Architecture: docs/contributors/architecture/index.md
    - IDE Testing: docs/contributors/ide_testing/index.md
  - Roadmap: roadmap/index.md
  - Blog: blog/index.md
  - Community: community/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/airbnb/viaduct
      name: GitHub
    - icon: fontawesome/solid/comments
      link: https://github.com/airbnb/viaduct/discussions
      name: Discussions
    - icon: fontawesome/solid/scale-balanced
      link: https://airbnb.tech/uncategorized/code-of-conduct/
      name: Code of Conduct
  analytics:
    provider: google
    property: G-79P40SMGG8
  privacy_policy: https://www.airbnb.com/help/article/3175
